# Generated by Django 4.2.4 on 2023-08-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_buddyships'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=919612461696, max_length=15),
            preserve_default=False,
        ),
    ]
