# Generated by Django 4.2.4 on 2023-08-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_count',
            field=models.IntegerField(default=0),
        ),
    ]
