# Generated by Django 4.2.4 on 2023-08-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_buddy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddy',
            name='unregistered',
            field=models.BooleanField(default=False),
        ),
    ]
