# Generated by Django 4.2.4 on 2023-08-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_buddy_unregistered'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddy',
            name='contact_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
